# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build APIs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]
defaults:
  run:
    working-directory: packages/pwafire
jobs:
  Build:
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run install
      - run: npm run build
